# Generated by Django 3.0.8 on 2020-07-18 22:56

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', django_editorjs.fields.EditorJsField()),
            ],
        ),
    ]
